language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"

install:
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn
  - pip install future
  - pip install .
  - pip install pytest pytest-cov coverage coveralls

script:
  - pytest --cov seglearn

after_success:
- coveralls
