language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest pytest-cov coverage coveralls

script:
  - pytest --cov pyts

after_success:
- coveralls
