version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo -E apt-get -yq remove texlive-binaries --purge
            sudo apt-get update
            sudo apt-get install libatlas-dev
            sudo apt-get install build-essential python-dev python-setuptools
            pip install --upgrade numpy
            pip install --upgrade scipy matplotlib setuptools nose coverage sphinx pillow sphinx-gallery sphinx_rtd_theme

            sudo -E apt-get -yq update
            sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra
            pip install --upgrade cython numpydoc
            pip install --upgrade scikit-learn
    deployment:
      push:
        branch: master
        commands:
          - bash ci_scripts/circleci/push_doc.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
